### PR TITLE
fix: prevent duplication of models from multiple ActiveRecord application classes

### PR DESCRIPTION
**Pull request by FraDim**
When the application defines multiple ActiveRecord application classes (for example [`ApplicationRecord`, as Rails documentation currently suggests](https://guides.rubyonrails.org/active_record_basics.html#creating-active-record-models)), the Forest schema contains duplicates of their subclass fields. It seems that the problem stems from a couple of innocent looking code lines:
 - The use of `subclasses` (which only gets direct children) in for the starting point:
 https://github.com/ForestAdmin/forest-rails/blob/d6d381d208335c54056a5dfea0db2281758041cb/lib/forest_liana/bootstrapper.rb#L111 and `descendants` (which gets direct and indirect children) in others:
 https://github.com/ForestAdmin/forest-rails/blob/d6d381d208335c54056a5dfea0db2281758041cb/lib/forest_liana/bootstrapper.rb#L117 and https://github.com/ForestAdmin/forest-rails/blob/d6d381d208335c54056a5dfea0db2281758041cb/lib/forest_liana/bootstrapper.rb#L120

 - The addition of models in the `ForestLiana.models` array when it might already contain them:
 https://github.com/ForestAdmin/forest-rails/blob/d6d381d208335c54056a5dfea0db2281758041cb/lib/forest_liana/bootstrapper.rb#L124
 It seems that some previous code tried to avoid this by using `uniq`:
 https://github.com/ForestAdmin/forest-rails/blob/d6d381d208335c54056a5dfea0db2281758041cb/lib/forest_liana/bootstrapper.rb#L139
 but I think we can prevent those issues (and probably more of the same kind downstream) by allowing only unique models in the array.

I have created two commits:
 - The first one adds and modifies some tests that expose the issue, but does not correct it. This will allow reviewers to see how it manifests.
 - The second one contains my suggested fix.

Please let me know if I should rebase them into one commit.

### General

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [x] Test manually the implemented changes
- [x] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [x] Consider the security impact of the changes made

### CODE REVIEW

**Comment by jeffladiray** [comment]
Hey @FraDim :wave: and thanks for your contribution on our rails agent 👍

The team will need a bit of time to investigate on both of your contribution (This one and [this one](https://github.com/ForestAdmin/forest-rails/pull/567)), mainly to make sure they match our requirements & that they do not introduce any breaking change.

We will let you know once everything is ready or if any changes are required?

Thanks 🙏

**Comment by matthv** [comment]
Hi @Fradim, thanks for your contribution 💪.

I ran the tests but some of them failed, could you please take a look?

**Comment by FraDim** [comment]
Thanks for informing me @matthv. I have reworked the tests now. Can you please run them again?

**Review by matthv — COMMENTED** [review]
Sounds good 💪 .
Thank you for your contribution.

**Pull request merged**
