### PR TITLE
feat(ruby): make repo compatible with ruby 3.2

### PR DESCRIPTION
**Pull request by lostie**
The existing source was using a method (`File.exists?`) that was deprecated in Ruby `2.1.10` and has been removed in Ruby 3.2 (more info [here in the release notes](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/)). The replacement `File.exist?` is supported since Ruby `1.8.6` and it is the recommended way to perform the same check.

Additionally, I have also updated the Rails version used for the gem's development/test.

### General

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [x] Test manually the implemented changes
- [x] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [x] Consider the security impact of the changes made

### CODE REVIEW

**Comment by lostie** [comment]
Hi @SteveBunlon, is it possible to get someone from ForestAdmin to review this PR? 🙇

**Comment by matthv** [comment]
Hi @lostie.
Thanks a lot for your contribution 💪. I would like to have more information about the migration to ruby 3.2.
The last commit seems to me good by replacing the old deprecated method `exists` ⭐.

However is it necessary to modify the minimum rails 6 version and move the routing tests?

if the last commit is enough on your side (to run the agent on 3.2), it would be better to create a PR just on this subject.

**Comment by lostie** [comment]
Hi @matthv,

Sorry, I should have provided a little bit more context on the changes, here it is:

* When running the test using Ruby `2.7.6` (which I believe is the ruby version you're testing the gem against) I'm able to run the tests successfully:

```shell
> ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin22]

> RAILS_ENV=test bundle exec rake --trace db:migrate test
** Invoke load_app (first_time)
** Execute load_app

# Running:

.....forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.forest-rails/app/models/forest_liana/model/collection.rb:26: warning: instance variable @is_searchable not initialized
.

Finished in 0.037629s, 425.2040 runs/s, 2099.4446 assertions/s.
```


* With the single commit that fixes the use of `File.exists?` I was not able to even get the tests to run when using Ruby `3.2.0`:

```shell
> ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]

> RAILS_ENV=test bundle exec rake --trace db:migrate test
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
** Invoke load_app (first_time)
** Execute load_app
rake aborted!
NameError: uninitialized class variable @@schemes in URI
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/globalid-0.4.2/lib/global_id/uri/gid.rb:176:in `<module:URI>'
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/globalid-0.4.2/lib/global_id/uri/gid.rb:6:in `<top (required)>'
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
```

That is the main reason I ended up updating the Rails version as a mean to be able to successfully run the tests (I guess the Rails version you're currently using is also not compatible with the most recent Ruby 3.X version):

```shell
> ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]

RAILS_ENV=test bundle exec rake --trace db:migrate test
** Invoke load_app (first_time)
** Execute load_app
** Invoke db:migrate (first_time)
** Invoke load_app
** Invoke app:db:migrate (first_time)
** Invoke app:db:load_config (first_time)
** Invoke app:environment (first_time)
** Execute app:environment
** Execute app:db:load_config
** Execute app:db:migrate
** Invoke app:db:_dump (first_time)
** Execute app:db:_dump
** Invoke app:db:schema:dump (first_time)
** Invoke app:db:load_config
** Execute app:db:schema:dump
** Execute db:migrate
** Invoke test (first_time)
** Execute test
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.1.7/lib/active_support/core_ext/class/subclasses.rb:30: warning: method redefined; discarding old subclasses
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/date_time_parser.rb:837: warning: statement not reached
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/date_time_parser.rb:691: warning: assigned but unused variable - testEof
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/address_lists_parser.rb:32457: warning: statement not reached
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/address_lists_parser.rb:32618: warning: statement not reached
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/address_lists_parser.rb:32654: warning: statement not reached
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/address_lists_parser.rb:32743: warning: statement not reached
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/address_lists_parser.rb:32759: warning: statement not reached
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/address_lists_parser.rb:32825: warning: statement not reached
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/address_lists_parser.rb:32866: warning: statement not reached
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/address_lists_parser.rb:32891: warning: statement not reached
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/mail-2.8.0/lib/mail/parsers/address_lists_parser.rb:31987: warning: assigned but unused variable - testEof
/forest-rails/lib/forest_liana/engine.rb:82: warning: possibly useless use of :: in void context
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/forestadmin-jsonapi-serializers-2.0.0.pre.beta.2/lib/jsonapi-serializers/serializer.rb:86: warning: method redefined; discarding old base_url
/forest-rails/lib/forest_liana/collection.rb:192: warning: method redefined; discarding old active_record_class
/forest-rails/lib/forest_liana/engine.rb:14: warning: method redefined; discarding old to_preflight_headers
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:421: warning: previous definition of to_preflight_headers was here
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ipaddress-0.8.3/lib/ipaddress.rb:72: warning: mismatched indentations at 'end' with 'unless' at 70
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ipaddress-0.8.3/lib/ipaddress/prefix.rb:81: warning: mismatched indentations at 'end' with 'class' at 21
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ipaddress-0.8.3/lib/ipaddress/ipv4.rb:647: warning: method redefined; discarding old multicast?
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ipaddress-0.8.3/lib/ipaddress/ipv4.rb:633: warning: previous definition of multicast? was here
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:370: warning: assigned but unused variable - pathlen
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:51: warning: method redefined; discarding old initialize
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_cert
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_file
/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_path
/forest-rails/config/initializers/logger.rb:29: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
Run options: --seed 34406

# Running:

...............

Finished in 0.019375s, 774.1936 runs/s, 825.8065 assertions/s.
15 runs, 16 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by lostie** [comment]
To add to the above:

* I have just updated the Rails version of the `Gemfile`, which only affects the development and testing environment. 
* I haven't made changes to the [forest_liana.gemspec](https://github.com/ForestAdmin/forest-rails/blob/064e8476c9c8f5977c428647dfe67d44e01249c8/forest_liana.gemspec#L20), which is the file that defines the Rails dependency version for the apps that use the gem. TLDR: This means that the apps don't have to update their Rails version to use the changes of this PR.

**Comment by matthv** [comment]
Hi @lostie, thanks for the feedback 👍  
I've running the tests but it seems that there are 2 regressions.
Could you have a look on it ?

**Review by matthv — APPROVED** [review]
Hi @lostie, sorry for the late reply.
I have just accepted your contribution, thank you very much again 💪 .

**Pull request merged**
