### PR TITLE
[+] Rails Versions - Support Rails 6 projects

### PR DESCRIPTION
**Pull request by arnaudbesnier**
## Pull Request checklist:

- [x] Write an explicit title for the Pull Request
- [x] Write changes made in the CHANGELOG.md
- [ ] Create automatic tests
- [ ] No automatic tests failures
- [x] Test manually the implemented changes
- [x] Review my own code (indentation, syntax, style, simplicity, readability)
- [x] Wonder if you can improve the existing code

### CODE REVIEW

**Comment by arnaudbesnier** [comment]
Fixes https://github.com/ForestAdmin/forest-rails/issues/314

**Comment by arnaudbesnier** [comment]
Fixes https://github.com/ForestAdmin/forest-rails/issues/329

**Comment by arnaudbesnier** [comment]
> All good to me I tested this out : it indeed breaks on rails v5.2.3 for example. With your fix it works like a charm for v6.0.0 (both creating/updating and collection detection).
> 
> Just a short note : after upgrading from v5.2.3 to v6.0.0, rails added this in application.rb
> 
> ```
> class Application < Rails::Application
>   # Initialize configuration defaults for originally generated Rails version.
>   config.load_defaults 5.2
> end
> ```
> 
> It might be worth warning people about that for newbies like me on rails, as the app won't start with this error : `block in load_missing_constant': uninitialized constant ForestLiana::Engine::Zeitwerk`.
> 
> Maybe this is something we should add in the migration guide , IDK.
> 
> I let you close the github issues after you merge this 👍

@SteveBunlon what do you mean by " it indeed breaks on rails v5.2.3"? Should I worry about a retro-compatibility issue?

To prevent the error after an upgrade, we should check dynamically the existence of `Zeitwerk` before calling it.
I'll improve the current, I initially had this in mind.

**Comment by SteveBunlon** [comment]
My bad I was mistaken : without your fix it breaks on rails v6, with it, it works well.

**Pull request merged**
